spring:
  cloud:
    stream:
      bindings:
        input:
          destination: config.simulateur
          group: simulateur
          binder: rabbit1
        inputObserver:
          destination: config.simulateur.simulateur
          group: simulateur
          binder: rabbit1
        inputDatabase:
          destination: config.simulateur.database
          group: simulateur
          binder: rabbit1
        outputObserver:
          destination: config.simulateur.observer
          group: observeur
          binder: rabbit1
        outputFacadeError:
          destination: config.facade.error
          group: facade
          binder: rabbit1
        outputDatabase:
          destination: config.database
          group: database
          binder: rabbit1
        outputFacade:
          destination: config.facade.simulateur
          group: facade
          binder: rabbit1
        outputDatabaseId:
          destination: config.database.id
          group: database
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest

server:
  port: ${PORT:2226}
