spring:
  cloud:
    stream:
      bindings:
        inputConfig:
          destination: config.facade
          binder: rabbit1
        inputSimulateurError:
          destination: config.facade.error
          binder: rabbit1
        outputSimulateur:
          destination: config.simulateur
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.14
                port: 5672
                username: docko
                password: docko
                
server:  
  port: ${PORT:2223}