version: '2'

services:
  webconfig:
    image: trafficflow/webweb:latest
    ports:
          - "2225:8080"

  facade:
    image: trafficflow/facade:latest
    ports:
          - "2223:8080"

  simulateur:
    image: trafficflow/simulateur:latest
    ports:
          - "2226:8080"

  observateur:
    image: trafficflow/observateur:latest
    ports:
          - "2227:8080"