spring:
  cloud:
    stream:
      bindings:
        output:
          destination: config.facade
          group: config
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.14
                port: 5672
                username: docko
                password: docko
server:
  port: ${PORT:2225}
