spring:
  cloud:
    stream:
      bindings:
        output:
          destination: config.facade
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.43.80
                port: 5672
                username: guest
                password: guest
server:
  port: ${PORT:2225}