spring:
  cloud:
    stream:
      bindings:
        input:
          destination: config.simulateur.observer
          group: observeur
          binder: rabbit1
        output:
          destination: config.simulateur.simulateur
          group: simulateur
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest

server:
  port: ${PORT:2227}
