spring:
  cloud:
    stream:
      bindings:
        input:
          destination: config.simulateur.observer
          binder: rabbit1
        output:
          destination: config.simulateur.simulateur
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.212.118.49
                port: 5672
                username: docko
                password: docko

server:
  port: ${PORT:2227}